"""
TDB output formatting for thermodynamic fitting results.

Logic is extracted from ``demo/gibbsfit.py`` (``format_tdb_parameter``) and
``demo/etotfit.py`` (``format_tdb_func``, ``_pad``).
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from emtdb.fitters.base import FitResult


def format_tdb_parameter(
    phase: str,
    elements: list[str],
    metrics: list[float],
    expression: str,
) -> str:
    """Build a ``PARAMETER G(phase,elem1:elem2:…;0)`` line.

    Parameters
    ----------
    phase:
        Phase name in upper case (``"BCC"``, ``"FCC"``, …).
    elements:
        Element symbols in upper case (e.g. ``["FE", "CR"]``).
    metrics:
        Normalised sublattice stoichiometry (must sum to 1).
    expression:
        SGTE expression string (e.g. ``"+1.23E+05-4.56E+01*T+…"``).

    Returns
    -------
    str
        A complete TDB parameter line terminated by ``"N !"``.

    Example
    -------
    ``PARAMETER G(BCC,FE:CR;0) 1.00 +1.23E+05-…-0.5*GHSERFE#-0.5*GHSERCR#; 6000.00 N !``
    """
    elems_str = ":".join(e.upper() for e in elements)
    ser_terms = "".join(
        f"-{m:.4g}*GHSER{_pad(e)}#"
        for e, m in zip(elements, metrics)
    )
    return (
        f"PARAMETER G({phase.upper()},{elems_str};0) 1.00"
        f" {expression}{ser_terms}; 6000.00 N !"
    )


def format_tdb_func(elem: str, expression: str) -> str:
    """Format a ``FUNCTION GHSER{XX}`` line for a pure-element SER reference.

    Parameters
    ----------
    elem:
        Element symbol (e.g. ``"NB"``, ``"V"``).
    expression:
        SGTE expression string.

    Returns
    -------
    str
        A complete TDB function line terminated by ``"N !"``.

    Example
    -------
    ``FUNCTION GHSERNB  1.00 +1.23E+05-4.56E+01*T+…; 6000.00 N !``
    """
    padded = _pad(elem)
    return (
        f"FUNCTION GHSER{padded}  1.00 {expression}; 6000.00 N !"
    )


def format_tdb_etser(elem: str, e0_j: float) -> str:
    r"""Format a ``FUNCTION ETSER{XX}`` line for a BM3 SER reference.

    Parameters
    ----------
    elem:
        Element symbol (e.g. ``"NB"``, ``"V"``).
    e0_j:
        Ground-state energy in J/mol.

    Returns
    -------
    str
        ``FUNCTION ETSER{pad}   1.00 {e0_j:+E}; 6000.00 N !``
    """
    padded = _pad(elem)
    return f"FUNCTION ETSER{padded}  1.00 {e0_j:+E}; 6000.00 N !"


def format_tdb_param_with_etser(
    phase: str,
    elements: list[str],
    metrics: list[float],
    e0_j: float,
) -> str:
    r"""Build a ``PARAMETER G(…)`` line using ETSER references for BM3 results.

    Parameters
    ----------
    phase:
        Phase name in upper case.
    elements:
        Element symbols.
    metrics:
        Normalised sublattice stoichiometry (sums to 1).
    e0_j:
        Ground-state energy in J/mol.

    Returns
    -------
    str
        ``PARAMETER G(…) 1.00 {e0_j:+E}{ser_ref}; 6000.00 N !``
    """
    comp_str = ":".join(e.upper() for e in elements)
    ser_ref = "".join(
        f"-{m:.4g}*ETSER{_pad(e)}#" for e, m in zip(elements, metrics)
    )
    return (
        f"PARAMETER G({phase.upper()},{comp_str};0)   1.00"
        f" {e0_j:+E}{ser_ref}; 6000.00 N !"
    )


def _pad(elem: str) -> str:
    """Pad an element symbol to exactly two characters.

    Single-letter symbols are repeated (e.g. ``"V"`` → ``"VV"``,
    ``"W"`` → ``"WW"``).  Two-letter symbols are returned unchanged.

    This matches the convention used in TDB function names such as
    ``GHSERVA`` and ``ETSERCR``.
    """
    s = elem.strip().upper()
    if len(s) >= 2:
        return s
    return s.ljust(2, s[-1])


def write_tdb_file(
    path: str | Path,
    results: list[FitResult],
    description: str = "fitted",
) -> None:
    """Write a complete TDB file from a list of ``FitResult``\\s.

    SER results become ``FUNCTION ETSER{XX}`` lines; non-SER produce a
    ``PHASE`` definition followed by ``PARAMETER G(…)`` lines (with ETSER
    references).  A TDB header with ``TYPE_DEFINITION`` is emitted.
    """
    results_sorted = sorted(results, key=lambda r: (r.phase != "SER", r.name))

    with open(path, "w", encoding="utf-8") as f:
        f.write(f"$ Thermodynamic database generated by emtdb.fitters\n")
        f.write(f"$ {len(results)} end-member(s) — {description}\n")
        f.write("$ \n")
        f.write(" TYPE_DEFINITION % SEQ * !\n\n")

        ser_results = [r for r in results_sorted if r.phase.upper() == "SER"]
        param_results = [r for r in results_sorted if r.phase.upper() != "SER"]

        if ser_results:
            f.write("$ ── SER reference functions ──\n")
            for r in ser_results:
                f.write(r.tdb_line + "\n")
            f.write("\n")

        if param_results:
            f.write("$ ── Phase parameters ──\n")

            # Write one PHASE definition per unique phase.
            seen_phases: set[str] = set()
            for r in param_results:
                ph = r.phase.upper()
                if ph not in seen_phases:
                    seen_phases.add(ph)
                    n_sub = len(r.metrics)
                    metrics_str = " ".join(f"{m:.4g}" for m in r.metrics)
                    f.write(f"PHASE {ph} % {n_sub} {metrics_str} !\n")
                f.write(" " + r.tdb_line + "\n")
